name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # يعمل يوميًا لتحديث الصورة
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: azzam06  # استبدل باسم المستخدم الخاص بك
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
